name: Integration Tests

on:
  pull_request:
    branches: [main]
    types: [labeled, opened, synchronize, reopened]
  push:
    branches: [main]
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: >-
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'

    - name: Download dependencies
      run: go mod download

    - name: Run integration tests
      env:
        SKYLIGHT_EMAIL: ${{ secrets.SKYLIGHT_EMAIL }}
        SKYLIGHT_PASSWORD: ${{ secrets.SKYLIGHT_PASSWORD }}
        SKYLIGHT_FRAME_ID: ${{ secrets.SKYLIGHT_FRAME_ID }}
      run: go test -v -tags integration -count=1 -timeout 5m ./lib/...
